FROM gettyimages/spark:2.3.0-hadoop-2.8

RUN pip install --upgrade setuptools -i https://mirrors.aliyun.com/pypi/simple && \
    pip install wheel -i https://mirrors.aliyun.com/pypi/simple && \
    pip install pyspark==2.3.0 -i https://mirrors.aliyun.com/pypi/simple
