FROM gettyimages/spark:2.3.0-hadoop-2.8

RUN  python3 -m pip install --upgrade setuptools && \
     pip install wheel -i https://pypi.tuna.tsinghua.edu.cn/simple && \
     pip3 install pyspark==2.3.0 -i https://pypi.tuna.tsinghua.edu.cn/simple
