FROM gettyimages/spark:2.3.0-hadoop-2.8

RUN pip install --upgrade setuptools -i https://pypi.tuna.tsinghua.edu.cn/simple && \
    pip install wheel -i https://pypi.tuna.tsinghua.edu.cn/simple 
RUN pip3 install pyspark==2.3.0 -i https://pypi.tuna.tsinghua.edu.cn/simple
